### ISSUE TITLE
Overriding framework styles with bootstrap by "important" attribute not working anymore

### ISSUE THREAD

**Issue by timothy-isenegger** [einpraegsam/powermail#591] opened 2020-09-28 12:32 UTC
## Expected Behavior
My constants look like the following configuration

```
## Bootstrap classes for powermail
plugin.tx_powermail.settings.styles.bootstrap.important = 1
plugin.tx_powermail.settings.styles.bootstrap.formClasses =
plugin.tx_powermail.settings.styles.bootstrap.fieldAndLabelWrappingClasses = row form-group
plugin.tx_powermail.settings.styles.bootstrap.fieldClasses = form-control
plugin.tx_powermail.settings.styles.bootstrap.labelClasses = col-12 col-form-label
plugin.tx_powermail.settings.styles.bootstrap.fieldWrappingClasses = col-12
plugin.tx_powermail.settings.styles.bootstrap.submitClasses = btn btn-primary btn-submit
plugin.tx_powermail.settings.styles.bootstrap.radioClasses = custom-control custom-radio custom-control-inline
plugin.tx_powermail.settings.styles.bootstrap.checkClasses = custom-control `custom-checkbox
```
With the first line, I expect these classes to be in my HTML output.

## Current Behavior
The HTML has the default classes configured by Powermail.

## Steps to Reproduce
1. Downgrade to Powermail 8.1.4
2. Copy my code from above or implement overrides with bootstrap yourself, see if the HTML renders correctly
3. Upgrade to Powermail 8.2.0
4. Check the HTML again - the classes from step 2 are not present anymore.

## Context (Environment)
TYPO3 10.4.8
Powermail 8.2.0

We are using only the main template from powermail in the static includes, no powermail_bootstrap or powermail_frontend (we are doing that by ourselves in a site package).

## Possible Implementation
Check your latest changes from the 8.1.4 to 8.2.0 -> it seems that you moved the code from the main setup.typoscript to a specific typoscript file, maybe there is no include to use the code?

**Comment by mschwemer** [comment] 2020-09-30 13:29
My last pull request is the cause for this behaviour. 

I move some TypoScript lines from `Main/setup.typoscript` to `BootstrapClassesAndLayout/setup.typoscript`.

My goal was to avoid a condition in TypoScript on the one side. 

On the other side I assumed, that everybody includes the addtional "TypoScript from Extension", when using the BootstrapClassesAndLayout stuff. Thus the condition for the BootstrapClasses seemed to be at the wrong place and could be avoided. 

Reading your bug report, I can confirm, that it is a breaking change. 

I'll talk to Alex.

**Comment by mschwemer** [comment] 2020-09-30 13:54
We talked and decided to leave the release as is, because it is semantically more correct, than the previous solution. 

But it is not hard to make your code future proof :-) You have got two possibilities:

* add the static typoscript for "BootstrapClassesAndLayout" to your installation (via "Template" => "Info/Modify" => Tab "Includes" or in the typoscript code of your site package) or
* copy the moved (now missing) code to your TypoScript setup 
   https://github.com/einpraegsam/powermail/blob/c134c6e2e347b8d20d7d8e2734b1c90f7cd8f40a/Configuration/TypoScript/BootstrapClassesAndLayout/setup.typoscript#L9-L31

**Comment by einpraegsam** [comment] 2020-10-03 09:33
Thx Marcus for digging into it. I will close this issue.

**Closed by einpraegsam** 2020-10-03 09:33 UTC
