### ISSUE TITLE
Sending mail from punycode domain

### ISSUE THREAD

**Issue by sxbxstxxn** [einpraegsam/powermail#301] opened 2018-07-03 07:07 UTC
I have a multiple Domain Typo3 8.7. The powermail formular works fine. Except when I use it in the section with the punycode domain (there is an ä in it). Typo3 automatically creates the punycode in the backend. But the logs from mail sending contains the following:

`Mon, 02 Jul 2018 16:09:27 +0200 [CRITICAL] request="48c027e568ecd" component="In2code.Powermail.Controller.FormController": Mail could not be sent - ["This is already a Punycode string"]`

So powermail say "it is a punycode, i cannot transform it" but typo3 automatically is transforming... or am I wrong?

**Comment by einpraegsam** [comment] 2018-07-03 09:46
I have really no idea what "punycode" is but mails are send with the core swiftmailer. If there are problems, this would be related to the core and not to powermail in my eyes.

**Comment by sxbxstxxn** [comment] 2018-07-04 06:52
punycode is what happend if you have a Domain with a "ä" oder "ö" or something.
see: https://en.wikipedia.org/wiki/Punycode
I think it IS a powermail problem because the powermail controller works with this punycode... or better it doesn't work with it. It wants to create the punycode from the domain, but this is what typo3 already do... so then there is an error message like "This is already a Punycode string".
Just try to create a powermail form in a section with a Domain like www.hände.de. You will not able to send a mail with powermail.

**Comment by einpraegsam** [comment] 2018-07-04 08:15
I can't reproduce the issue on my system sorry

**Comment by sxbxstxxn** [comment] 2018-07-11 10:02
I'm trying to change the sender_mail ... but if I sent the mail it's always noreply@domäne.de. I tried following in the typoscript:

`plugin.tx_powermail.settings.setup.sender.email = noreply@domäne.de

plugin.tx_powermail.settings.receiver.overwrite.senderName.value = noreply0
plugin.tx_powermail.settings.receiver.overwrite.senderEmail.value = noreply0@domäne.de

plugin.tx_powermail.settings.receiver.default.senderName.value = noreply0b
plugin.tx_powermail.settings.receiver.default.senderEmail.value = noreply0b@domäne.de

plugin.tx_powermail.settings.receiver.overwrite.returnPath = noreply0c@domäne.de
plugin.tx_powermail.settings.receiver.overwrite.replyToEmail = noreply0d@domäne.de


plugin.tx_powermail.settings.sender.overwrite.senderName.value = noreply1
plugin.tx_powermail.settings.sender.overwrite.senderEmail.value = noreply1@domäne.de

plugin.tx_powermail.settings.sender.default.senderName.value = noreply1b
plugin.tx_powermail.settings.sender.default.senderEmail.value = noreply1b@domäne.de

plugin.tx_powermail.settings.sender.overwrite.returnPath = noreply1c@domäne.de
plugin.tx_powermail.settings.sender.overwrite.replyToEmail = noreply1d@domäne.de`

but if I look in the database table "tx_powermail_domain_model_mail" there is always the same sender_mail after sending it from frontend form. In the plugin there is no entry for the sender...

Any ideas?

**Comment by einpraegsam** [comment] 2018-07-11 15:03
No, sorry

**Comment by einpraegsam** [comment] 2018-07-13 19:56
Maybe domains with umlauts are not supported by TYPO3 or by the swiftmailer or by powermail. Nevertheless at the moment there are not plans to analyze this issue in a deep way.
I'm going to close this issue now, but feel free to do a debugging or a PR if it will help.

**Closed by einpraegsam** 2018-07-13 19:56 UTC
