### ISSUE TITLE
CSV export generates inconsistent output

### ISSUE THREAD

**Issue by K1LLUM1N471** [einpraegsam/powermail#270] opened 2018-05-09 13:30 UTC
TYPO3 v8.7.10
powermail 6.0.0

When filling in the form and leaving a field empty, the CSV generator does not add a semicolon for that field, so that the content of the CSV file is inconsistent, because of slips of data sets. The XLS export works like a charm.

Expectation:
";" ";"[Content of field]

Result:
";"[Content of field]

Perhaps this (unwanted) event can be found in 'powermail/Resources/Private/Templates/Module/ExportCsv.html'.

Do you have any clues?

Thank you in advance, 
K1LLUM1N471

**Comment by wowawebdesign** [comment] 2018-06-13 12:31
I can confirm this problem in Powermail 6.0.0.

**Comment by einpraegsam** [comment] 2018-07-13 20:05
Sorry for my late answer.
I just tested in my local testparcours, but the result was as expected:
```
"Vorname";"Nachname";"E-Mail";
"Alex";"";"alexander.kellner@einpraegsam.net";
"Alex";"Kellner";"alexander.kellner@einpraegsam.net";
"Alex";"Kellner";"alexander.kellner@einpraegsam.net";
```
What did I do to reproduce the issue: 
Filling out a form with three fields (every field is filled). And after that again, but I skipped `Nachname`. The export was ok in my eyes. What else can I do for a reproduction?

**Comment by wowawebdesign** [comment] 2018-07-16 06:41
Hm, I reproduced your simple example and here the export was ok too. But I have a more complex form in a customers project with select boxes, checkboxes etc., and here the problem still exists.

**Comment by baden32** [comment] 2018-08-23 07:17
Hi Alex, thanks for your reply. But actually what can be done if such changes have been done on the form? Export is definitely brocken? I have the same problem with a form having 20 fields. If not required fileds areempty, then the csv export is brocken because of ";" missing for these empty fields.
Are you working on a solution?

**Comment by einpraegsam** [comment] 2018-08-23 07:25
No, I'm not working on a solution right now. Nevertheless feel free to contribute (pull requests, sponsoring, etc...)

**Comment by einpraegsam** [comment] 2019-01-10 13:03
Sorry, but I tested again and can't find a problem. I will close this issue now. This does not mean that there is no issue or there is no interest in fixing a possible problem. Anyways: Feel free to add pull requests.

**Closed by einpraegsam** 2019-01-10 13:03 UTC

**Comment by xerc** [comment] 2020-06-29 20:25
![Bildschirmfoto 2020-06-29 um 22 19 16](https://user-images.githubusercontent.com/1372590/86052064-ad8eeb80-ba56-11ea-8364-0c49b9e8283c.png)
if you have three fields and middel is not mandatory and therefore not filled
TRUE will remove this field and the third fild is displaced to the second one

$removeEmptyValues
@ https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/core/Classes/Utility/GeneralUtility.php#L977

**Comment by xerc** [comment] 2020-06-29 21:04
PLEASE import this PATCH also to v7 // THX

**Comment by matthaa** [comment] 2023-08-10 08:01
With radio buttons the problem still exists. 
Example with 5 radio buttons if all 5 are filled out, CSV output looks like this:
"foo";"foo";"foo";"foo";"foo";
If only 3 are filled out:
"foo";"foo";"foo";
expected is:
"foo";"foo";"foo";"";"";
Powermail 10.7.0
TYPO3 11.5.30
PHP 8.1.
non composer installation

**Comment by matthaa** [comment] 2023-08-10 13:26
The error seems to occur only in the CSV files, the XLS files are working.
