### ISSUE TITLE
Condition isPowermailOnCurrentPage - Call to a member function getLanguage()

### ISSUE THREAD

**Issue by agendartobias** [einpraegsam/powermail#604] opened 2020-10-09 13:20 UTC
Hello, every time i click something in TYPO3 BE i get this error in log:

`[ERROR] request="dd4661a52839e" component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Call to a member function getLanguage() on null - {"expression":"isPowermailOnCurrentPage()","exception":{}}`

TYPO3 10.4.7
Powermail 8.2.1

Can anyone help?

**Comment by einpraegsam** [comment] 2020-10-12 12:40
I can't reproduce this issue. And normally I'm not going to fix issues that I can't see. Nevertheless I can imaging what the problem is and I think we should fix this issue.
Pushed a fix to develop branch - ready for upcoming release

**Closed by einpraegsam** 2020-10-12 12:40 UTC
