### ISSUE TITLE
Backend record icons missing

### ISSUE THREAD

**Issue by mkrappitz** [einpraegsam/powermail#93] opened 2017-05-22 08:21 UTC
In TYPO3 7.6.18, php 7.0.latest, powermail 3.19.0 the icons of all powermail records are missing, resp. displaying the red "broken icon" icon:
![grafik](https://cloud.githubusercontent.com/assets/5528239/26298382/5a3a2600-3ed7-11e7-92f9-82e226901d02.png)

Using the icon registry in ext_localconf.php like this, the icons do display again:

```
...
$iconRegistry = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Core\Imaging\IconRegistry::class);
$iconRegistry->registerIcon('ext-powermail-field', \TYPO3\CMS\Core\Imaging\IconProvider\BitmapIconProvider::class, ['source' => 'EXT:powermail/Resources/Public/Icons/tx_powermail_domain_model_field.gif']);
...
```

Then of course also change the icon handling in ctrl part of e.g. EXT:powermail/Configuration/TCA/tx_powermail_domain_model_field.php:
```
...
// 'iconfile' => ConfigurationUtility::getIconPath(Field::TABLE_NAME . '.gif')
'typeicon_classes' => [
    'default' => 'ext-powermail-field'
],
...
```

No idea why this seems to be necessary now. Saw it being done like this in EXT:news, where icons worked in the same TYPO3 installation.

**Comment by einpraegsam** [comment] 2017-05-22 08:32
Thx for the feedback. I will check this asap.

**Comment by mkrappitz** [comment] 2017-05-22 08:34
Of course it might also be a core bug, that the old way of setting up icons generally fails.

**Comment by einpraegsam** [comment] 2017-06-06 19:33
I updated my old testparcours to 7.6.18, cleared all caches in Install Tool, removed all files in typo3temp/* but the icons still existing.
How to reproduce this issue?

**Comment by mkrappitz** [comment] 2017-06-07 07:00
I dug a bit deeper into this and finally found out, that this problem comes only up once you install EXT:news 5.3.3 or 6.0.0. Probably this messes something up in the way Georg uses the icon factory. Sorry for reporting. Not quite sure if I should report this for EXT:news.

**Comment by einpraegsam** [comment] 2017-06-07 09:08
Hmm ok - so I will close this issue for now. I'm not sure if the problem is related to news, the core or powermail because of a wrong usage of icons

**Closed by einpraegsam** 2017-06-07 09:08 UTC

**Comment by cweiske** [comment] 2021-01-20 14:32
I had the same problem on TYPO3 v7 with the focuspoint extension. It uses the "autoloader" extension (v3.2.0), which instantiates the IconRegistry in its ext_localconf.php. The registry then knows no TCA tables, and thus cannot register icons for extension tables.
