### ISSUE TITLE
Error when using only SendPost without sender- and receivermail

### ISSUE THREAD

**Issue by SimonWentland** [einpraegsam/powermail#238] opened 2018-02-14 14:36 UTC
With the new Update a new Error has appeared.
Using only **SENDPOST** **without** **mail to user** and **without** **mail to receiver**.
**Returning** from the Submit Page AND then hitting **refreshing** in the Browser the Error appears.

But Form has been send correctly. 

Was not there in older versions.

![bildschirmfoto 2018-02-14 um 15 08 46](https://user-images.githubusercontent.com/13437564/36209631-80d2c2d4-119c-11e8-8aa9-a325f7dae8b1.jpg)

**Comment by einpraegsam** [comment] 2018-02-21 16:01
Pls tell me your TypoScript configuration and show me your FlexForm configuration. I would like to reconstruct the issue on my testsystem.

**Comment by SimonWentland** [comment] 2018-02-22 09:44
Hope this helps
![sendpost](https://user-images.githubusercontent.com/13437564/36531141-3a609b06-17bd-11e8-8528-040f07a50d29.jpg)

**Comment by einpraegsam** [comment] 2018-03-27 11:27
Sorry, I can't reproduce it with the latest powermail version and T3 8.7.
Did you turned of sending mails via TypoScript like 
```
plugin.tx_powermail.settings.setup {
	receiver.enable = 0
	sender.enable = 0
	db.enable = 0
}
```

**Comment by einpraegsam** [comment] 2018-05-01 10:01
Probably a side-effect together with your settings. Nevertheless, I will close this issue for now.

**Closed by einpraegsam** 2018-05-01 10:01 UTC

**Comment by sneopu** [comment] 2018-09-03 10:01
I think the problem still exists in the actual version.

To reproduce:
- plugin.tx_powermail.settings.setup.receiver.enable = 1
- Flexform: Receiver Email empty
- Flexform: Receiver Subject empty ( the label says it disable the email sending)

In my eyes the problem is in the SendMailService (https://github.com/einpraegsam/powermail/blob/develop/Classes/Domain/Service/Mail/SendMailService.php), function sendMail() line 70ff
=> The validation on the $email['receiverEmail'] should be after the "if (empty($email['subject']))" because it validates the email and generate the error flashmessage, but there is no email sent because of the empty subject which does not generate a error message
