### ISSUE TITLE
TypeError in In2code\Powermail\Utility\TypoScriptUtility::overwriteValueFromTypoScript()

### ISSUE THREAD

**Issue by KreativeKrise** [einpraegsam/powermail#649] opened 2021-03-03 12:46 UTC
If I open the opt-in mail and click the disclaimer link to delete the request, I get the following error:

`Argument 2 passed to In2code\Powermail\Utility\TypoScriptUtility::overwriteValueFromTypoScript() must be of the type array, null given, called in /typo3conf/ext/powermail/Classes/Domain/Service/Mail/SendMailService.php on line 447`

TYPO3 10.4.13
powermail 8.3.0

Quickfix:

Change line 27 in `Classes/Utility/TypoScriptUtitility.php` to `?array $conf = [],`.

**Comment by cdaecke** [comment] 2021-03-30 18:35
I can confirm this bug. The above quickfix works for me.

TYPO3 10.4.14
powermail: 8.3.0

**Comment by christian-fries** [comment] 2021-04-29 16:18
Same issue here with TYPO3 10.4.15 and powermail 8.3.1

**Comment by einpraegsam** [comment] 2021-04-30 07:07
PR https://github.com/einpraegsam/powermail/pull/655 just merged into develop - ready for upcoming release

**Closed by einpraegsam** 2021-04-30 07:07 UTC
