### ISSUE TITLE
Start Time and End Time are automatically set when saving an Object in the Backend

### ISSUE THREAD

**Issue by siwa-tkapplmueller** [einpraegsam/powermail#696] opened 2021-07-21 10:40 UTC
When saving a Form, Page, Field, Answer or Mail in the Backend the Start and End Times are automatically set. Everytime you try to remove said dates, they are automatically set again.

This bug only seems to appear with TYPO3 v10.4.18. When i remove the `range` from the TCA config of those two columns, everything works again.

Also, in the TCA Configurations of that columns, the property `checkbox` is still used, even though that property is officially not used anymore since TYPO3 4.5:
https://docs.typo3.org/m/typo3/reference-tca/7.6/en-us/Reference/Columns/Input/Index.html#checkbox

**Comment by nebrot** [comment] 2021-07-21 10:59
I think it has something to do with this core-patch https://review.typo3.org/c/Packages/TYPO3.CMS/+/69776

**Comment by peerlight** [comment] 2021-07-23 12:10
see also https://forge.typo3.org/issues/94621

**Comment by einpraegsam** [comment] 2021-07-27 19:58
Thx for your feedback. I will close this issue because it is related to a core problem.

**Closed by einpraegsam** 2021-07-27 19:58 UTC

**Comment by georgringer** [comment] 2021-07-30 18:00
this is also resolved with https://github.com/einpraegsam/powermail/pull/698, so please just update powermail. thx @einpraegsam for the release

**Comment by einpraegsam** [comment] 2021-08-05 08:56
Thx to @georgringer the latest powermail version 8.3.3 should fix the bug if someone don't want to wait for a TYPO3 regression update.
