### ISSUE TITLE
Bug in parsley validation with no cache

### ISSUE THREAD

**Issue by kamilmaliszewski** [einpraegsam/powermail#382] opened 2019-01-11 10:15 UTC
**Start info:**
TYPO3 9.5LTS
PHP7.2
Powermail 7.0 (6.2 also the same)

**Description**
When cache is not generated (only 1-st entry) the powermail generate wrong values in form input and validation works incorrect. If e.g first field is set as "required", then attribute "data-parsley-required" will be added to all fields into form even they are not mandatory. In the result the validation works wrong. It's not JS fail, the inputs are generated with wrong tags.

**How to reproduce:**
1. Enable Parsley.js validation in powermail
2. Create powermail form with 3 fields:
- Text input with validation rule e.g "e-mail"
- Text input without validation rule or just "mandatory"
- Submit button
3. Clear the cache
4. Enter to the page with powermail plugin and try to submit empty form

**What will happen?**
At both fields will be error that "This field should be e-mail"

**What should will happen?**
At first field error "This field should be e-mai"
At 2nd field no error or "this field is required" -> depends on the config

**Comment by einpraegsam** [comment] 2019-01-11 11:19
I just tested with TYPO3 9.5 and powermail 7.0 and my behaviour is completely different.
Creating such a form:
* Text with email-validation
* Text without validation
* Submit

And if I submit, it will submit the form. Why: Because it's not needed to fill out a field with only a email-validation.

----

Next test:

* Text with email-validation
* Text with mandatory validation
* Submit

If I submit (with cleaned caches before), only the second field shows the error message:
<img src="https://s.nimbusweb.me/attachment/2442670/lpx4turh7vundmoo5fxh/PwtBixSXD3tU21FW/screen.png" />

----

What else should I do to reproduce this issue?

**Comment by einpraegsam** [comment] 2019-01-11 11:42
Thx, I could reproduce this issue now:
<img src="https://s.nimbusweb.me/attachment/2442766/fuoq15mq12xekflg9t3q/KKm1nJfPwC6dxrkq/screen.png" />

The downside to this: At the moment I have no idea what's wrong with the uncached content.

**Comment by kamilmaliszewski** [comment] 2019-01-11 11:52
@einpraegsam I am not sure if it's TYPO9.5 fail or Powermail ext. I lost all day to debug it but I did not find any intresting thing. Just connection with no cache and make sure that it is not JS.

**Comment by einpraegsam** [comment] 2019-01-11 11:55
Yes, you're right. I'm also looking at TYPO3 core or on FLUID, but same here - could not find a fix while searching.

**Comment by DavidBruchmann** [comment] 2019-01-17 14:10
So could my issue #383 be a base for a fix?

**Comment by DavidBruchmann** [comment] 2019-02-04 03:32
Any progress here?
Never like to hack every installation with my quick-fix ...

**Comment by benjaminpick** [comment] 2019-03-05 14:57
This is fixed in Typo3 9.5.5 - probably by https://github.com/TYPO3/Fluid/pull/419 ...
@DavidBruchmann Can you confirm this is fixed (without your patches)?

**Comment by einpraegsam** [comment] 2019-04-09 12:10
Can anyone confirm the message from @benjaminpick?

**Comment by kamilmaliszewski** [comment] 2019-04-09 12:23
I have TYPO 9.5.4 and Powermail 7.2.0 now and it seems to work correctly. 
When I was adding this issuse I had TYPO 9.5.1 and Powermail 7.0.0, so it is not 9.5.5, but 9.5.2; 9.5.3 or 9.5.4 @benjaminpick  @einpraegsam

**Comment by einpraegsam** [comment] 2019-04-09 12:39
Thx, so I will close this issue

**Closed by einpraegsam** 2019-04-09 12:39 UTC
