### ISSUE TITLE
Upload size problem

### ISSUE THREAD

**Issue by xbouillet** [einpraegsam/powermail#745] opened 2022-03-22 08:55 UTC
Hello,

We use a TYPO3 in 11.5.6, and we use powermail version in early access.
The constant plugin.tx_powermail.settings.misc.uploadSize doesnt'work.
We want the file size to be less than 2mb..

The constant doesn't seem to work.
After sending the form, if the file is very large, there are no messages or blocking

Any help please?

Thanks

**Comment by mschwemer** [comment] 2022-04-25 07:22
Unfortunately I cannot reproduce this here. I tested it with a file size limit of 30kB and a file size 34,9 kB. The file upload is blocked on server side and on client side. 

Did you activate the feature in the settings?

```
plugin.tx_powermail {
	settings {
		setup {
			validation {
				native = 1
				server = 1
				client = 1
			}
		}
	}
}
```

**Comment by einpraegsam** [comment] 2022-06-06 17:09
I'm going to close this issue because of no feedback

**Closed by einpraegsam** 2022-06-06 17:09 UTC
