### ISSUE TITLE
E-Mails not being sent if senderHeader not set

### ISSUE THREAD

**Issue by samsauter** [einpraegsam/powermail#430] opened 2019-04-26 08:21 UTC
### Expected behaviour
senderHeader.name & senderHeader.email for both sender and receiver should be optional values. (At least if I understand the [Documentation](https://docs.typo3.org/typo3cms/extensions/powermail/ForAdministrators/BestPractice/MainTypoScript/Index.html?highlight=senderheader) correctly)
I'd expect these values to be filled from the plugin / flexform config in case I do not configure them in Typoscript.

### Actual behaviour
Without explicitly setting values in contstants for
```
plugin.tx_powermail.settings.sender.senderHeader.email
plugin.tx_powermail.settings.sender.senderHeader.name
plugin.tx_powermail.settings.receiver.senderHeader.email
plugin.tx_powermail.settings.receiver.senderHeader.name
```
no e-mail is sent.

### Possible problematic code
`powermail/Classes/Domain/Service/Mail/SendMailService.php@addSenderHeader()`. The condition `if(GeneralUtility::validEmail($email)){…}` will never be true if there is no value set. The sender is not set for the message.

### System
TYPO3 9.5.5
Powermail 7.2.0

### Possible related issue 
#394 sounds a lot like the issue I was facing. I could resolve my issue by setting the above mentioned values in Typoscript.

**Comment by mschwemer** [comment] 2020-12-04 11:54
Unfortunately I am not able to reproduce this behaviour.

RFC 822 says, that the sender header is only required, if there are multiple FROM: headers in one email.  See: https://tools.ietf.org/html/rfc2822#section-3.6.2

Can you provide more details about your setup? Especially regarding the configuration of the FROM addresses / headers?

**Comment by samsauter** [comment] 2020-12-09 13:17
"Multiple FROM" could actually have been the problem. I honestly don't remember anymore. If nobody else is facing the issue, you can probably just close it.

**Comment by mschwemer** [comment] 2021-02-05 12:35
Thanks :-) I close it now

**Closed by mschwemer** 2021-02-05 12:35 UTC
