### ISSUE TITLE
Type error if filesize during upload process is returning false

### ISSUE THREAD

**Issue by Mainbird** [einpraegsam/powermail#693] opened 2021-07-08 08:58 UTC
Hi :)

if the filesize call inside:

https://github.com/einpraegsam/powermail/blob/8.3.2/Classes/Domain/Factory/FileFactory.php#L135

will fail, then the setSize call inside:

https://github.com/einpraegsam/powermail/blob/8.3.2/Classes/Domain/Factory/FileFactory.php#L137

will fail too, because of the wrong type. 

Maybe, it would be safe to cast the filesize here:

```
$size = (int)filesize($file->getNewPathAndFilename(true));
```

or place another condition after this call to ensure the correct type:

```
if ($size === false) {
    $size = 0;
}
$file->setSize($size);
```

What do you think? :)

**Comment by s0njar0** [comment] 2021-07-19 09:53
+1
Our logs keep getting flooded with error messages like this, caused by some funny dudes with gmail addresses:

`Core: Error handler (FE): PHP Warning: filesize(): stat failed for /uploads/tx_powermail/pittmanrhiannon97_gmail.com in /typo3conf/ext/powermail/Classes/Domain/Factory/FileFactory.php line 135`

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Argument 1 passed to In2code\Powermail\Domain\Model\File::setSize() must be of the type int, bool given, called in /typo3conf/ext/powermail/Classes/Domain/Factory/FileFactory.php on line 137 | TypeError thrown in file /typo3conf/ext/powermail/Classes/Domain/Model/File.php in line 241.`

**Comment by einpraegsam** [comment] 2021-07-27 19:55
Thx, will be fixed in the upcoming release

**Closed by einpraegsam** 2021-07-27 19:55 UTC
