### ISSUE TITLE
Powermail form (ajaxSubmit) gets submitted mulitple times 

### ISSUE THREAD

**Issue by elmarputz** [einpraegsam/powermail#211] opened 2017-12-19 16:18 UTC
On TYPO3 8.7.9 we have a single step form with ajax submit. After updating to 4.3.2 the form suddenly was submitted exactly 3 times. We got the mails 3 times and 3 distinct records got stored in the database. The issue appears with version 4.3.2 and above, 4.3.1 is not affected. We do not have any custom JS events registered on the submit button, its a basic form template.

**Comment by einpraegsam** [comment] 2017-12-20 08:00
Hi, that sounds very strange to me. The only change between 4.3.1 and 4.3.2 is a revert of a change in the FlexForm. Nothing related to frontend. 
I tried it on my testsystem with the latest powermail and everything works as expected.
Can you give me some more information:
1) Which browser is affected?
2) Did you clean all caches in Install Tool after upgrading?
3) Do you have more then only 1 powermail form on the webpage?
4) Do you not use the original Forms.js from powermail but your own?
5) Are there any extensions that extends powermail?

**Comment by elmarputz** [comment] 2017-12-20 08:14
Hi, 
i think we found the problem: in our configuration, we had the following setup: 

- Ajax Submit was enabled: `plugin.tx_powermail.settings.misc.ajaxSubmit = 1`
- In the plugin, we had a redirect page configured via flexform (which is the desired behaviour) 

After disabling ajaxSubmit, the form gets processed only once and the redirect works as expected. It seems that redirecting in combination with ajax submit does not work together (which doesn't make sense anyway), but before 4.3.1 this was not a problem. 

Thanks for your support!

**Comment by einpraegsam** [comment] 2017-12-20 08:57
Thx, I can confirm this issue and will have a look at it asap.

**Comment by einpraegsam** [comment] 2017-12-20 10:15
I just tested revision by revision. The problem was introduced with https://github.com/einpraegsam/powermail/commit/456317540c34e3c444a23623f393d21b9647555b
It seems that the current content uid is needed for the redirectServer class and this got lost with it.
Shame on me, I will push a fix asap.

**Comment by einpraegsam** [comment] 2017-12-20 10:19
Thx for reporting this issue. I pushed a fix to develop branch. Ready for an upcoming release.

**Closed by einpraegsam** 2017-12-20 10:19 UTC
