### ISSUE TITLE
Overwrite senderEmail doesn't work as expected

### ISSUE THREAD

**Issue by W4ldgeist** [einpraegsam/powermail#716] opened 2021-09-23 15:32 UTC
receiver.overwrite.senderEmail in constants only works if the field in the form is not configured to be the senderEmail. The problem with that is that using the email of the user who filled out a form as a "from" address will trigger Spamfilters as the webserver is usually not allowed to send emails from the domains of the users, who fill out forms.

We usually worked through that by using receiver.overwrite.senderEmail + not setting senderEmail. Now we have the use case to have an Admin email + a user email, which only works if the senderEmail is marked in the form. Once it's marked, the admin email will be marked as spam, due to the behaviour described above.

I think the overwrite settings should actually always overwrite the settings set anywhere else and it should be reviewed if it ever makes sense to set From as the user address, due to Spamrules on most mailservers.

**Comment by mschwemer** [comment] 2021-10-01 14:45
Duplicate of #692

**Closed by mschwemer** 2021-10-01 14:45 UTC
