### ISSUE TITLE
Disclaimer mail doesn't use correct sender mail

### ISSUE THREAD

**Issue by bavarianbytes** [einpraegsam/powermail#692] opened 2021-07-08 07:26 UTC
`disclaimerAction()` in `Classes/Controller/FormController.php` sends an email to the receiver if a user deletes his database entry.
If your mail server only accepts a real email address due SPF and you use `receiver.overwrite.senderEmail.value` in TypoScript to overwrite the sender mail address, this defined address is not used to send the disclaimer mail. Instead the mail address in the form field is used.
So the disclaimer view ends with end exception and the database entry is not deleted.

**Comment by W4ldgeist** [comment] 2021-09-23 15:42
Just found this, after I wrote this report. They seem to have the same issue at heart: Duplicate of #716

**Comment by W4ldgeist** [comment] 2021-11-22 14:52
I think the general problem lies in: SendReceiverMailPreflight.php. There the same getter is used for SenderEmail and ReployTo Email. For E-Mail to work properly SenderEmail and SenderName should never (!) be the user name and user email that's wrong for email server rules.

The present mechanic uses the user information to configure sendermail and sendermail. That causes SPF failures and Admin mails being marked as SPAM. This should not even be a configuration, the default needs to be a configured value or taken from the SenderMail Setting in the Flexform that is used for the UserEmail.

**Comment by LimeUwe** [comment] 2021-11-22 20:50
While I agree that it is an issue, that the default configuration invites to run into SPF defience problems, it's addressed in the documentation for quite some time here:
https://github.com/einpraegsam/powermail/blob/develop/Documentation/FAQ/Readme.md#how-to-solve-spf-defiance

**Comment by W4ldgeist** [comment] 2021-11-23 06:16
That's nice, but these settings don't work. That's the bug.

**Comment by mschwemer** [comment] 2022-04-25 09:33
@bavarianbytes I can confirm the issue. 

There are some more SPF and `overwrite` related issues. We need to take a deeper look into that topic.

**Closed** 2022-06-06 17:18 UTC

**Comment by rschumachr** [comment] 2023-07-20 09:45
I'm currently experiencing the same issue. (using Powermail v10.7.2 on Typo3 11.5)

When trying to use the opt-out link in the confirmation mail the following error is logged: "_554 5.2.252 SendAsDenied; noreply@email.com not allowed to send as emailUsedToSignUp@random.com_" indicating that it's trying to send the email with the client address as the sender instead of the noreply address that I've defined in the following places:

plugin.tx_powermail.settings.setup.sender.overwrite.senderEmail.value = noreply@email.com
plugin.tx_powermail.settings.setup.receiver.overwrite.senderEmail.value = noreply@email.com
plugin.tx_powermail.settings.setup.optin.overwrite.senderEmail.value = noreply@email.com

The confirmation link in the opt-in e-mail is working perfectly. It only happens with the opt-out link at the bottom. It also happens regardless if I first confirm the opt-in or directly try to opt-out without confirming.

Not sure if I'm doing something wrong here or if there is still an issue with Powermail and the opt-out link to delete your data.
