### ISSUE TITLE
Detailed plugin information inside pageview causes conflicts with non-extbase extensions

### ISSUE THREAD

**Issue by aprettser** [einpraegsam/powermail#193] opened 2017-11-13 14:36 UTC
Hello,
there is an issue with the detailed plugin-preview of powermail. The reson for that is that powermail reads the flexform of all embeeded plugins/contentelements. This leads to errors as soon as someone uses a non-exbase-extension, where a dot ('.') in a value-key-part of a flexform is present.
The issue happens inside the FlexFormService.php on line 47, where the character of the explode() function is set to a dot.
The initialize() method inside PluginPreview.php should only be called for powermails own plugin and not for all contentelements, which are present. That way other non-extbase extensions will stop having the conflict with powermail.
This is only noticable if the option "Disable Plugin Information" is turned off

**Comment by einpraegsam** [comment] 2017-11-13 15:35
Pls tell me which TYPO3 and which powermail version do you use.
In the current one the plugin preview is only rendered if:
- Plugin Information is not disabled in extension manager settings
- tt_content.CType of the content element is set to `list`
- tt_content.list_type is set to `powermail_pi1` or `powermail_pi2`

**Comment by rengaw83** [comment] 2017-11-14 09:11
We use powermail 3.22.1 and TYPO3 7.6 at the moment. But i think this problem occurs in the current powermail 4.1 too. The Hook has not canged since 3.22.

The problem is that `In2code\Powermail\Hooks\PluginPreview->initialize` renders the flexform and is always called. 
So the flexform will be rendered for each tt_content element on a page throu `TYPO3\CMS\Extbase\Service\FlexFormService\FlexFormService::convertFlexFormContentToArray`.  If there is a non extbase based plugin like t3users or mksearch, the flexform of these plugins will be rendered by the powermail plugin preview hook. But this can results in an fatal php error in the extbase flexform service.

Only after the initialization the ctype and list_type is checked.

The plugin preview hook must not render the flexform of each tt_content element on a page. 
The `convertFlexFormContentToArray` call should be outsourced to a new method and should only be called for the relevant powermail elements.

**Comment by einpraegsam** [comment] 2017-11-14 09:19
Now I understand the problem. I will fix this asap in an upcoming release. Thx for digging into that issue.

**Comment by einpraegsam** [comment] 2017-11-14 09:28
I pushed a fix to develop branch. Ready for upcoming release.

**Closed by einpraegsam** 2017-11-14 09:28 UTC

**Comment by rengaw83** [comment] 2017-11-14 09:31
Thanks a lot. We will test this during the week.

**Comment by rengaw83** [comment] 2017-11-14 12:29
We have testet the last fix now. Works as expected! Thank you!
Will you release this fix in 4.x only or in 3.x too?

**Comment by einpraegsam** [comment] 2017-11-14 13:33
The fix will be only release for 4.x
