### ISSUE TITLE
Bug in powermail 7.1.0 - PrefillFieldViewHelper

### ISSUE THREAD

**Issue by peterbenke** [einpraegsam/powermail#389] opened 2019-01-23 14:17 UTC
Hello,

**Environment:**
TYPO3: 8.7.22
powermail: 7.1.0
php: 7.1.26

**Description:**
I have a field country, which gets the list from static_countries (own partial Country.html):
_value="{vh:Misc.PrefillField(field:field)}"_

**I get the following exception:**
Argument 1 passed to In2code\Powermail\ViewHelpers\Misc\PrefillFieldViewHelper::getFromDefaultValue() must be of the type string, integer given, called in /var/www/html/http/typo3conf/ext/powermail/Classes/ViewHelpers/Misc/PrefillFieldViewHelper.php on line 115

This is the new function getFromDefaultValue in powermail/Classes/ViewHelpers/Misc/PrefillFieldViewHelper.php (in powermail 7.0.0 everything works fine).

I think, you should change the function from:

`protected function getFromDefaultValue(string $value): string`
to:
`protected function getFromDefaultValue($value)`

Thanks.

**Comment by birgitrg** [comment] 2019-01-24 17:00
Same problem with prefilled feuser.uid

**Comment by foobar13372** [comment] 2019-02-01 11:05
Same with a custom field.

**Comment by Raemy92** [comment] 2019-02-06 15:18
I have the same problem but it seems only in IE with cleared cache.
After the error message I have to clear the cache to have this error again.

Couldn't reproduce this in other browsers.

**Comment by foobar13372** [comment] 2019-02-07 06:34
@Raemy92 
This is a server-side problem (PHP) independent from browser. We have XClassed
`\In2code\Powermail\ViewHelpers\Misc\PrefillFieldViewHelper`
and
`\In2code\Powermail\Utility\FrontendUtility`
to hotfix it (by casting explicitly to string).

The problem is a type-mismatch.

**Comment by Raemy92** [comment] 2019-02-07 07:49
Thanks for your explanations, @foobar13372.

Since I could only reproduce this error with IE and cleared cache, I thught it could be a browser problem. My client also tested it with several browsers and had this issue only with IE.

I now changed the code as suggested by @peterbenke and waiting for any feedbacks.

**Comment by foobar13372** [comment] 2019-02-08 11:06
The solution should not be the removing of the return type. It should actuaklly be to ensure a consistent and reliable type (string). Which can be achived in the two classes I mentioned above.

**Comment by einpraegsam** [comment] 2019-02-18 13:52
Thx for your time that you've spent into that issue. For now I simply removed the typehint. The better way for the future is to set typehints to all functions within the class, but that will be done in a later commit.
Will be released with the upcoming version

**Closed by einpraegsam** 2019-02-18 13:52 UTC
