### ISSUE TITLE
mark one field as mandatory all fields in one page get mandatory

### ISSUE THREAD

**Issue by Uhradone** [einpraegsam/powermail#415] opened 2019-03-22 21:44 UTC
I use pages and if in a page one field gets mandatory all fields will get a warning if they are not filled. The little star (*) indicator works correct, but the validation has a wrong behavior.
Only if all fields in a page don't have mandatory it is fine.

TYPO3 9.5.4
Powermail 7.2.0

Made some more tests:
If you uncheck all fields and save it and do an empty run of the form. And then check your fields you want to be mandatory again it seems to work that only the mandatory fields get a warning.

**Comment by benjaminpick** [comment] 2019-03-23 12:11
Duplicate of #382 - this should be fixed in Typo3 9.5.5 ...

**Closed** 2019-03-25 08:44 UTC
